"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

export default function Dashboard(){
 const[profile,setProfile]=useState<any>(null),[auditions,setAuditions]=useState<any[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/login";return;}const[{data:p},{data:a}]=await Promise.all([supabase.from("profiles").select("*").eq("id",user.id).single(),supabase.from("auditions").select("id,entry_title,status,submitted_at,competitions(title,category)").eq("participant_id",user.id).order("submitted_at",{ascending:false})]);setProfile(p);setAuditions(a||[]);setLoading(false);})()},[]);
 async function logout(){await supabase.auth.signOut();window.location.href="/";}
 const active=auditions.filter(x=>["submitted","under_review","qualified"].includes(x.status)).length,qualified=auditions.filter(x=>x.status==="qualified").length;
 if(loading)return <div className="shell"><main className="container page"><div className="notice">Loading your dashboard…</div></main></div>;
 return <div className="shell"><nav className="nav"><Link href="/" className="brand">talento<span>.</span></Link><div className="navlinks"><Link href="/competitions">Competitions</Link><Link href="/organizer">Organizer</Link></div><button className="btn ghost" onClick={logout}>Logout</button></nav><main className="container page"><h1>My dashboard</h1><p className="muted">Welcome, {profile?.full_name||"Talento participant"}.</p><div className="kpis" style={{margin:"25px 0"}}><div className="card kpi"><b>{active}</b><p className="muted">Active auditions</p></div><div className="card kpi"><b>{qualified}</b><p className="muted">Qualified rounds</p></div><div className="card kpi"><b>0</b><p className="muted">Wins</p></div><div className="card kpi"><b>0</b><p className="muted">Certificates</p></div></div><div className="panel"><div className="sectionhead"><div><h2>My auditions</h2><p className="muted">Submission and qualification status.</p></div><Link className="btn primary" href="/competitions">Find competition</Link></div>{auditions.length===0?<div className="notice">No auditions submitted yet.</div>:<div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Entry</th><th>Competition</th><th>Submitted</th><th>Status</th></tr></thead><tbody>{auditions.map(a=><tr key={a.id}><td>{a.entry_title||"Untitled"}</td><td>{a.competitions?.title||"Competition"}</td><td>{new Date(a.submitted_at).toLocaleDateString("en-IN")}</td><td><span className="pill">{a.status.replace("_"," ")}</span></td></tr>)}</tbody></table></div>}</div><div className="grid" style={{marginTop:18}}><div className="panel"><h3>My profile</h3><p className="muted">{profile?.email||""}{profile?.phone?" · "+profile.phone:""}</p><span className="pill">{profile?.role||"participant"}</span></div><div className="panel"><h3>Organizer</h3><p className="muted">Create your own competition and manage its stages.</p><Link className="btn ghost" href="/organizer">Open organizer</Link></div></div></main></div>;
}